### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by simon-p-r** [bealearts/kerberos-agent#1]
Hi @DavidBeale 

Does this module work from Linux GSSAPI (client) to Windows host (SSPI)?

Best regards
Simon

**Comment by simon-p-r** [comment]
Update - I have tested this module from both Windows and Linux machine acting as client with node-sspi on server side.  I cannot get the handshake to complete, I will write my own module to handle sspi on client side.

Thanks

**Comment by DavidBeale** [comment]
Thanks for the update.

I currently use this in Production with node-sspi endpoints and .Net endpoints. As mentioned in the readme, the handshake is not yet implemented, but this is not always required.

I would assume with only works on a Windows client.

**Comment by simon-p-r** [comment]
Please excuse my ignorance as not mastered Kerberos and Windows auth but I couldn't get negotiate auth process working from either Linux or Windows host

**Comment by DavidBeale** [comment]
Windows Integrated Authentication is a pretty big and complex subject. Perhaps try getting off the shelf components to work first, such as IIS for the server and IE or curl for the client.
